project_id = "pvtamcqdadggkdazehbc"

[[functions]]
name = "send-application-email"
verify_jwt = false

[[functions]]
name = "send-contact-email"
verify_jwt = false

[[functions]]
name = "send-feedback-email"
verify_jwt = false

[[functions]]
name = "send-feedback-notification"
verify_jwt = false

[[functions]]
name = "send-referral-notifications"
verify_jwt = false

[[functions]]
name = "send-referral-verification"
verify_jwt = false

[[functions]]
name = "send-testimonial-email"
verify_jwt = false

[[functions]]
name = "send-testimonial-confirmation"
verify_jwt = false

[[functions]]
name = "validate-checkout"
verify_jwt = false