// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://pvtamcqdadggkdazehbc.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2dGFtY3FkYWRnZ2tkYXplaGJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI0MDcxMDMsImV4cCI6MjA0Nzk4MzEwM30.AH-8Godyda00v45f3UDuIwGQjLwh93u89rMO9eGVXmc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);